apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost-app
  labels:
    app: mattermost
    tier: app
  namespace: mattermost-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mattermost
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      name: mattermost-app
      labels:
        app: mattermost
        tier: app
    spec:
      #securityContext:
      #  runAsUser: 2000
      #  runAsGroup: 2000
      #  fsGroup: 2000
      containers:
      - name: mattermost-app
        image: "mattermost/mattermost-prod-app:5.16.4"
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mattermost-env
              key: db-host
        - name: DB_PORT_NUMBER
          valueFrom:
            secretKeyRef:
              name: mattermost-env
              key: db-port
        - name: MM_USERNAME
          valueFrom:
            secretKeyRef:
              name: mattermost-env
              key: mm-username
        - name: MM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mattermost-env
              key: mm-password
        - name: MM_DBNAME
          valueFrom:
            secretKeyRef:
              name: mattermost-env
              key: mm-dbname
        volumeMounts:
        - name: appdata
          mountPath: /mattermost/data
      # optional persistent storage
      initContainers:
        - name: pgsql-data-permission-fix
          image: busybox
          command: ["sh", "-c", "chown -R 2000:2000 /mattermost/data", "chgrp 2000 /mattermost/data"]
          volumeMounts:
            - name: appdata
              mountPath: /mattermost/data
      volumes:
      - name: appdata
        persistentVolumeClaim:
          claimName: mattermost-postgres-pvc
      #- name: etclocaltime
      #  hostPath:
      #    path: /etc/localtime
