apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
  namespace:
    mattermost-ns
data:
  POSTGRES_DB: mattermost
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin
