apiVersion: v1
kind: PersistentVolume
metadata:
  name: mattermost-postgres-pv
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
  labels:
    name: mattermost-postgres-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.10.10
    path: /mnt/mattermost/postgres
